### ISSUE TITLE
Sprites.bin

### ISSUE THREAD

**Issue by BacchusFLT** [intoinside/SpaceInvaders#13]
Building from scratch, the sprites arenät created. One needs to manually convert the spritepad file to a bin file ... Isn't that meant to be done in the build process? If not, I suggesting to have the spritepad file external to the project and import a bin file in a manual step.

**Comment by intoinside** [comment]
Yes you are right. Sprites.bin isn't created by gradle build (it requires an higher version of spritepad). I'll add in the next commit.
Thank you for reporting
